"use client";

import React, { useState } from "react";
import Link from "next/link";
import {
  UserCheck,
  Building2,
  QrCode,
  Smartphone,
  ArrowRight,
  ShieldCheck,
  CheckCircle2,
  Sparkles,
  Zap,
  Globe2,
  RefreshCw,
  Lock,
  ArrowUpRight,
  ArrowDownLeft,
  KeyRound,
  History
} from "lucide-react";

export const WorkflowSection: React.FC = () => {
  const [activeTab, setActiveTab] = useState<"send" | "receive">("send");

  const steps = [
    {
      number: "01",
      icon: <KeyRound className="w-6 h-6 text-emerald-400" />,
      title: "Log In & 1-Click KYC",
      desc: "User logs in, selects their bank, and completes instant Zero-Knowledge biometric verification. No repetitive paper forms.",
    },
    {
      number: "02",
      icon: <Globe2 className="w-6 h-6 text-emerald-400" />,
      title: "Select Destination Country",
      desc: "Choose the country you are traveling to or making payments for. RHI Pay auto-detects local payment rails and locks in real-time FX rates.",
    },
    {
      number: "03",
      icon: <QrCode className="w-6 h-6 text-emerald-400" />,
      title: "Send or Receive Money",
      desc: "Send money via unique QR generated by receiver, phone number, or unique code — or generate your own Dynamic QR to receive funds.",
    },
    {
      number: "04",
      icon: <History className="w-6 h-6 text-emerald-400" />,
      title: "Track History & FX Rates",
      desc: "Instantly track recent payments, full transaction history, multi-currency wallet balances, and live wholesale foreign exchange rates.",
    },
  ];

  return (
    <section id="workflow" className="py-20 bg-[#081C2D]/30 border-t border-white/[0.06] relative">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section Header */}
        <div className="text-center max-w-3xl mx-auto space-y-4 mb-16">
          <div className="inline-flex items-center gap-2 px-3.5 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/25 text-emerald-400 text-xs font-mono font-semibold">
            <Zap className="w-3.5 h-3.5" />
            <span>HOW IT WORKS</span>
          </div>

          <h2 className="text-3xl sm:text-5xl font-extrabold text-white tracking-tight leading-tight">
            Simple, Intuitive & <span className="text-gradient-emerald">Lightning Fast</span>
          </h2>

          <p className="text-base sm:text-lg text-[#9AA3A8]">
            From sign-in to instant global settlement in four straightforward steps.
          </p>
        </div>

        {/* 4-Step Cards Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-16">
          {steps.map((s, idx) => (
            <div
              key={idx}
              className="glass-panel p-6 rounded-3xl border border-white/[0.08] hover:border-emerald-500/35 transition-all flex flex-col justify-between group relative overflow-hidden"
            >
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <div className="w-12 h-12 rounded-2xl bg-emerald-500/10 border border-emerald-500/25 flex items-center justify-center group-hover:scale-110 transition-transform">
                    {s.icon}
                  </div>
                  <span className="text-2xl font-extrabold font-mono text-white/20 group-hover:text-emerald-400/40 transition-colors">
                    {s.number}
                  </span>
                </div>

                <h3 className="text-lg font-bold text-white group-hover:text-emerald-300 transition-colors">
                  {s.title}
                </h3>

                <p className="text-xs text-[#9AA3A8] leading-relaxed">
                  {s.desc}
                </p>
              </div>

              <div className="pt-4 mt-4 border-t border-white/[0.06] text-[11px] font-mono text-emerald-400 flex items-center gap-1.5">
                <CheckCircle2 className="w-3.5 h-3.5" />
                <span>Instant Confirmation</span>
              </div>
            </div>
          ))}
        </div>

        {/* Dual Role Workflow Breakdown: Send vs Receive */}
        <div className="glass-panel-glow p-8 sm:p-10 rounded-3xl border border-emerald-500/25 max-w-4xl mx-auto">
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 pb-6 border-b border-white/[0.08]">
            <div>
              <h3 className="text-xl font-bold text-white">
                Two Flexible Modes: Send or Receive
              </h3>
              <p className="text-xs text-[#9AA3A8] mt-1">
                Choose how you want to move money across borders in seconds.
              </p>
            </div>

            <div className="flex items-center gap-1 bg-[#040D14] p-1 rounded-2xl border border-white/10 flex-shrink-0">
              <button
                onClick={() => setActiveTab("send")}
                className={`flex items-center gap-1.5 px-4 py-2 text-xs font-bold rounded-xl transition-all ${
                  activeTab === "send"
                    ? "bg-emerald-500 text-black shadow-md shadow-emerald-500/30"
                    : "text-[#9AA3A8] hover:text-white"
                }`}
              >
                <ArrowUpRight className="w-3.5 h-3.5" />
                <span>Sender Experience</span>
              </button>

              <button
                onClick={() => setActiveTab("receive")}
                className={`flex items-center gap-1.5 px-4 py-2 text-xs font-bold rounded-xl transition-all ${
                  activeTab === "receive"
                    ? "bg-emerald-500 text-black shadow-md shadow-emerald-500/30"
                    : "text-[#9AA3A8] hover:text-white"
                }`}
              >
                <ArrowDownLeft className="w-3.5 h-3.5" />
                <span>Receiver Experience</span>
              </button>
            </div>
          </div>

          {/* Mode Details */}
          <div className="pt-6">
            {activeTab === "send" ? (
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 text-xs">
                <div className="p-4 rounded-2xl bg-[#040D14]/80 border border-white/[0.08] space-y-2">
                  <div className="font-bold text-white flex items-center gap-2">
                    <QrCode className="w-4 h-4 text-emerald-400" />
                    <span>Scan Dynamic QR</span>
                  </div>
                  <p className="text-[#9AA3A8] leading-relaxed">
                    Scan the recipient's dynamic QR code with exact amounts and instant FX lock.
                  </p>
                </div>

                <div className="p-4 rounded-2xl bg-[#040D14]/80 border border-white/[0.08] space-y-2">
                  <div className="font-bold text-white flex items-center gap-2">
                    <Smartphone className="w-4 h-4 text-emerald-400" />
                    <span>Phone or Code Pay</span>
                  </div>
                  <p className="text-[#9AA3A8] leading-relaxed">
                    Enter the payee's phone number or unique 6-digit payment code for instant transfer.
                  </p>
                </div>

                <div className="p-4 rounded-2xl bg-[#040D14]/80 border border-white/[0.08] space-y-2">
                  <div className="font-bold text-white flex items-center gap-2">
                    <History className="w-4 h-4 text-emerald-400" />
                    <span>Live Tracking & History</span>
                  </div>
                  <p className="text-[#9AA3A8] leading-relaxed">
                    Track payment status in real time, view full transaction history, and check wallet balance.
                  </p>
                </div>
              </div>
            ) : (
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 text-xs">
                <div className="p-4 rounded-2xl bg-[#040D14]/80 border border-white/[0.08] space-y-2">
                  <div className="font-bold text-white flex items-center gap-2">
                    <QrCode className="w-4 h-4 text-emerald-400" />
                    <span>Generate Dynamic QR</span>
                  </div>
                  <p className="text-[#9AA3A8] leading-relaxed">
                    Create custom QR requests with designated amounts, target currency, and purpose.
                  </p>
                </div>

                <div className="p-4 rounded-2xl bg-[#040D14]/80 border border-white/[0.08] space-y-2">
                  <div className="font-bold text-white flex items-center gap-2">
                    <Sparkles className="w-4 h-4 text-emerald-400" />
                    <span>Generate Unique Code</span>
                  </div>
                  <p className="text-[#9AA3A8] leading-relaxed">
                    Share a temporary 6-digit secure code with the payer for fast, seamless authorization.
                  </p>
                </div>

                <div className="p-4 rounded-2xl bg-[#040D14]/80 border border-white/[0.08] space-y-2">
                  <div className="font-bold text-white flex items-center gap-2">
                    <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                    <span>Track Incoming Funds</span>
                  </div>
                  <p className="text-[#9AA3A8] leading-relaxed">
                    Receive instant notifications as payments clear in sub-3s with automated receipts.
                  </p>
                </div>
              </div>
            )}

            <div className="pt-6 mt-6 border-t border-white/[0.08] flex items-center justify-between">
              <span className="text-xs text-[#9AA3A8]">
                Ready to experience seamless cross-border payments?
              </span>
              <Link
                href="/app"
                className="btn-pressable inline-flex items-center gap-2 px-5 py-2 text-xs font-bold text-black bg-emerald-400 hover:bg-emerald-300 rounded-xl shadow-md transition-all"
              >
                <span>Launch Hub</span>
                <ArrowRight className="w-3.5 h-3.5" />
              </Link>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};
